export const escrowAbi = [
  {
    type: "event",
    name: "EscrowCreated",
    inputs: [
      { name: "escrow_id", type: "address", internalType: "address", indexed: true },
      { name: "buyer", type: "address", internalType: "address", indexed: true },
      { name: "seller", type: "address", internalType: "address", indexed: true },
      { name: "amount", type: "uint64", internalType: "uint64", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "NewUID",
    inputs: [{ name: "uid", type: "bytes32", internalType: "bytes32", indexed: true }],
    anonymous: false,
  },
  {
    type: "function",
    name: "create",
    inputs: [
      { name: "seller", type: "address", internalType: "address" },
      { name: "amount", type: "uint64", internalType: "uint64" },
      { name: "deadline", type: "uint64", internalType: "uint64" },
      { name: "memo", type: "bytes", internalType: "uint8[]" },
      { name: "arbitrator", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "release",
    inputs: [{ name: "escrow", type: "bytes32", internalType: "struct Escrow.Escrow" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "refund",
    inputs: [{ name: "escrow", type: "bytes32", internalType: "struct Escrow.Escrow" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "buyer",
    inputs: [{ name: "escrow", type: "bytes32", internalType: "struct Escrow.Escrow" }],
    outputs: [{ type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "seller",
    inputs: [{ name: "escrow", type: "bytes32", internalType: "struct Escrow.Escrow" }],
    outputs: [{ type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "amount",
    inputs: [{ name: "escrow", type: "bytes32", internalType: "struct Escrow.Escrow" }],
    outputs: [{ type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "status",
    inputs: [{ name: "escrow", type: "bytes32", internalType: "struct Escrow.Escrow" }],
    outputs: [{ type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deadline",
    inputs: [{ name: "escrow", type: "bytes32", internalType: "struct Escrow.Escrow" }],
    outputs: [{ type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "memo",
    inputs: [{ name: "escrow", type: "bytes32", internalType: "struct Escrow.Escrow" }],
    outputs: [{ type: "bytes", internalType: "uint8[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "arbitrator",
    inputs: [{ name: "escrow", type: "bytes32", internalType: "struct Escrow.Escrow" }],
    outputs: [{ type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isPending",
    inputs: [{ name: "escrow", type: "bytes32", internalType: "struct Escrow.Escrow" }],
    outputs: [{ type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isExpired",
    inputs: [
      { name: "escrow", type: "bytes32", internalType: "struct Escrow.Escrow" },
      { name: "current_timestamp", type: "uint64", internalType: "uint64" },
    ],
    outputs: [{ type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
] as const;
